version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    restart: always 


  frontend:
    build: ./frontend
    container_name: frontend 
    ports:
      - '8501:8501'
    depends_on:
      - backend
    restart: always


